// 本地模拟json数据
var producationData = [
  
  
  [
    // 种类1
    {
      "producation_id": 1,
      "producation_type": 1,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 2,
      "producation_type": 1,
      "producation_originalPrice": 3300,
      "producation_name": 'C1 VIP包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 1,
      "producation_type": 1,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 2,
      "producation_type": 1,
      "producation_originalPrice": 3300,
      "producation_name": 'C1 VIP包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 1,
      "producation_type": 1,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 2,
      "producation_type": 1,
      "producation_originalPrice": 3300,
      "producation_name": 'C1 VIP包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 1,
      "producation_type": 1,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 2,
      "producation_type": 1,
      "producation_originalPrice": 3300,
      "producation_name": 'C1 VIP包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
  ],

  [
    // 种类2
    {
      "producation_id": 3,
      "producation_type": 2,
      "producation_originalPrice": 1000,
      "producation_name": 'VIP年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 4,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP季卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 5,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP4年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 6,
      "producation_type": 2,
      "producation_originalPrice": 100,
      "producation_name": 'VIP卡',
      "producation_cutdowmPrice": 30,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 7,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 3,
      "producation_type": 2,
      "producation_originalPrice": 1000,
      "producation_name": 'VIP年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 4,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP季卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 5,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP4年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 6,
      "producation_type": 2,
      "producation_originalPrice": 100,
      "producation_name": 'VIP卡',
      "producation_cutdowmPrice": 30,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 7,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 3,
      "producation_type": 2,
      "producation_originalPrice": 1000,
      "producation_name": 'VIP年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 4,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP季卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 5,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP4年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 6,
      "producation_type": 2,
      "producation_originalPrice": 100,
      "producation_name": 'VIP卡',
      "producation_cutdowmPrice": 30,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 7,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 3,
      "producation_type": 2,
      "producation_originalPrice": 1000,
      "producation_name": 'VIP年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 4,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP季卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 5,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP4年卡',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 6,
      "producation_type": 2,
      "producation_originalPrice": 100,
      "producation_name": 'VIP卡',
      "producation_cutdowmPrice": 30,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
    {
      "producation_id": 7,
      "producation_type": 2,
      "producation_originalPrice": 3000,
      "producation_name": 'C1包过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
  ],


  [  // 种类3
    {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '法语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '汉语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '英语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '德语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '毛利求雌语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '宇宙通用语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '法语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '汉语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '英语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '德语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '毛利求雌语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '宇宙通用语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '法语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '汉语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '英语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '德语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '毛利求雌语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '宇宙通用语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '法语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '汉语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '英语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '德语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '毛利求雌语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 3,
      "producation_originalPrice": 3000,
      "producation_name": '宇宙通用语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },

  ],

  [  // 种类4
    {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '托福',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '德福',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '法语托福',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": 'vip托福班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '必过托福班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '小班精品',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '1V1托福培训',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 4,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
  ],

  [  // 种类5
    {
      "producation_id": 1,
      "producation_type":5,
      "producation_originalPrice": 13000,
      "producation_name": '雅思初级班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思留学班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思高级班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '雅思VIP留学班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思必过班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思小班精品',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '1V1雅思培训',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type":5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '雅思包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '雅思包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '雅思精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type":5,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type":5,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 5,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
  ],


  [  // 种类67
    {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 13000,
      "producation_name": '小李快车',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '小鸡快卓',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '蓉姐爱车',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 13000,
      "producation_name": '昌飞尔',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '浑河哈哈车',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '小牛电动车',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 13000,
      "producation_name": '艾玛电动车',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }
    ], 
    
    [
    {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": '数学',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": '英语',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 13000,
      "producation_name": '政治',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 6,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type":7,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 13000,
      "producation_name": '包过班',
      "producation_cutdowmPrice": 1300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": '精品班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    }, {
      "producation_id": 1,
      "producation_type": 7,
      "producation_originalPrice": 3000,
      "producation_name": 'VIP班',
      "producation_cutdowmPrice": 300,
      "producation_des": "为您提供武汉最优质的服务",
      "producation_pic_url": "http://www.0311xc.cn/upload/jiaxiao/d/148924235671737_b.jpg",
    },
  ],
]


var ticketData=[
  {
    "producation_name":'武汉育才驾校C1普通班',
    "finalprice":'2980',
    "order_pingzheng":'321fo12Doi23df',   //预约凭证
    "orde_telephone":"13203221323",       //预约电话
    "state":0,      //0:进行中，，1：已结束
    "kindOfboat":0,   //0:小船 ， 1：大船
  },
  
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '3980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '1980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '2980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 1,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '1980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 1,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '1980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 1,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '1480',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 1,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '3980',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
  {
    "producation_name": '武汉育才驾校C1普通班',
    "finalprice": '4910',
    "order_pingzheng": '321fo12Doi23df',   //预约凭证
    "orde_telephone": "13203221323",       //预约电话
    "state": 0,      //0:进行中，，1：已结束
    "kindOfboat": 0,   //0:小船 ， 1：大船
  },
]
// 定义数据出口
module.exports = {
  producationData: producationData,
  ticketData:ticketData
}